// 发版说明：按 git diff --name-status 列出两个版本之间 src/icons 里新增、重画（修改）、删除的图标；
// 改名以两个版本之间 src/aliases.js 新增的条目为准（旧名 → 现名），git 的相似度检测（-M）只作兜底
// 用法：
//   node scripts/release-notes.mjs v0.4.0 v0.5.0      两个 tag（或任意提交）之间
//   node scripts/release-notes.mjs v0.5.0             上一个 tag 到 v0.5.0
//   node scripts/release-notes.mjs                    最新的 tag 到 HEAD（还没打 tag 的改动）
// 选项：
//   --title <名字>   小节标题（默认是终点的 tag 名，终点是 HEAD 时为 Unreleased）；发版前写 CHANGELOG 时给新版本号
//   --body           不带「## 标题」那一行（GitHub Release 的正文用）
//   --changelog      写进 CHANGELOG.md：插在最前面，已有同名小节就替换
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'

const REPO = 'https://github.com/Jannchie/jannchie-icons'
// stderr 收进异常里，不直接打到终端（比如旧版本里没有 src/aliases.js）
const git = (...args) => execFileSync('git', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }).trim()

const argv = process.argv.slice(2)
const flag = name => argv.includes(name)
const option = (name) => {
  const i = argv.indexOf(name)
  return i >= 0 ? argv[i + 1] : undefined
}
const positional = argv.filter((a, i) => !a.startsWith('--') && argv[i - 1] !== '--title')

// 某个提交上（含）最近的 v* tag；previousTag：这个提交之前的
const latestTag = ref => git('describe', '--tags', '--abbrev=0', '--match', 'v*', ref)
const previousTag = ref => latestTag(`${ref}^`)

let [from, to] = positional
if (positional.length === 1) {
  to = positional[0]
  from = previousTag(to)
}
else if (!positional.length) {
  to = 'HEAD'
  from = latestTag('HEAD')
}
const title = option('--title') ?? (to === 'HEAD' ? 'Unreleased' : to)

// 某个版本的别名表（src/aliases.js 是不依赖别的模块的纯数据，直接按 ES 模块求值）；那时还没有这个文件就是空表
async function aliasesAt(ref) {
  let source
  try {
    source = git('show', `${ref}:src/aliases.js`)
  }
  catch {
    return {}
  }
  return (await import(`data:text/javascript,${encodeURIComponent(source)}`)).ALIASES ?? {}
}
const [fromAliases, toAliases] = await Promise.all([aliasesAt(from), aliasesAt(to)])
// 新登记的旧名 → 现名（已有的旧名改指向别的名字不算新的改名）
const aliasRenames = new Map(Object.entries(toAliases).filter(([old]) => !(old in fromAliases)))
const renamedTo = new Set(aliasRenames.values())

// 只看图标文件；别名表里登记过的改名不再算新增 / 删除；没登记的按 git 的相似度检测（-M），改名同时改了形状也算改名
const iconName = path => path.match(/^src\/icons\/(.+)\.js$/)?.[1]
const added = []
const redrawn = []
const removed = []
const renamed = [...aliasRenames]
for (const line of git('diff', '--name-status', '-M', `${from}..${to}`, '--', 'src/icons').split('\n').filter(Boolean)) {
  const [status, a, b] = line.split('\t')
  // 改名在 git 里是一条 R（旧 → 新），也可能是一条 D 加一条 A：拆成删除 + 新增，再扣掉别名表里登记过的
  const [na, nb] = [iconName(a), b && iconName(b)]
  if (status.startsWith('R')) {
    if (na && nb && !aliasRenames.has(na) && !renamedTo.has(nb)) {
      renamed.push([na, nb])
      continue
    }
    if (na && !aliasRenames.has(na))
      removed.push(na)
    if (nb && !renamedTo.has(nb))
      added.push(nb)
    continue
  }
  if (!na)
    continue
  if (status === 'A') {
    if (!renamedTo.has(na))
      added.push(na)
  }
  else if (status === 'D') {
    if (!aliasRenames.has(na))
      removed.push(na)
  }
  else {
    redrawn.push(na)
  }
}

const code = names => names.sort().map(n => `\`${n}\``).join(', ')
const date = to === 'HEAD' ? new Date().toISOString().slice(0, 10) : git('log', '-1', '--format=%as', to)
const total = git('ls-tree', '--name-only', `${to}:src/icons`).split('\n').filter(f => f.endsWith('.js')).length
const sections = [
  added.length && `### Added (${added.length})\n\n${code(added)}`,
  redrawn.length && `### Redrawn (${redrawn.length})\n\n${code(redrawn)}`,
  removed.length && `### Removed (${removed.length})\n\n${code(removed)}`,
  renamed.length && `### Renamed (${renamed.length})\n\n${renamed.sort(([a], [b]) => (a < b ? -1 : 1)).map(([a, b]) => `- \`${a}\` → \`${b}\``).join('\n')}`,
].filter(Boolean)
const compareTo = to === 'HEAD' ? 'main' : to
const body = [
  `${total} icons in total. [Full diff](${REPO}/compare/${from}...${compareTo})`,
  ...(sections.length ? sections : ['No icon changes.']),
].join('\n\n')
const notes = flag('--body') ? `${body}\n` : `## ${title} (${date})\n\n${body}\n`

if (flag('--changelog')) {
  const FILE = 'CHANGELOG.md'
  const HEADER = '# Changelog\n\nIcon changes in each release, generated by `node scripts/release-notes.mjs` from `git diff --name-status` on `src/icons`.\n'
  const text = existsSync(FILE) ? readFileSync(FILE, 'utf8').replace(/\r\n/g, '\n') : HEADER
  // 按「## 」切成小节：第一段是文件头，其余每段一个版本
  const [head, ...rest] = text.split(/\n(?=## )/)
  const at = rest.findIndex(s => s.startsWith(`## ${title} (`))
  const parts = rest.map(s => s.trimEnd())
  // 已有同名小节就原地替换，否则插在最前面（新版本在上）
  if (at >= 0)
    parts[at] = notes.trimEnd()
  else
    parts.unshift(notes.trimEnd())
  writeFileSync(FILE, `${[head.trimEnd(), ...parts].join('\n\n')}\n`)
  console.log(`${FILE}: wrote ${title} (${from}..${to})`)
}
else {
  process.stdout.write(notes)
}
