// 侧栏（和窄屏的分类标签）里每个分类前面的代表图标
// 手挑最能一眼认出这一类的那个；没列出的分类、或者挑的图标已经不在这个分类里（改名、挪了分类），就取分类里的第一个图标
import { categorize } from './categories'
import { icons } from './iconset'

const PICKS = {
  'folder': 'folder',
  'file': 'file',
  'list': 'list',
  'mail': 'mail',
  'chat': 'chat',
  'monitor': 'monitor',
  'calendar': 'calendar',
  'briefcase': 'briefcase',
  'basic': 'plus',
  'arrow': 'arrow-right',
  'status': 'check-circle',
  'action': 'download',
  'editor': 'edit',
  'search': 'search',
  'glyph': 'letter-a',
  'greek': 'greek-alpha',
  'stem': 'stem-jia',
  'branch': 'branch-zi',
  'astro': 'astro-saturn',
  'zodiac': 'zodiac-aries',
  'chinese-zodiac': 'chinese-zodiac-dragon',
  'iching': 'trigram-qian',
  'moon-phase': 'moon-phase-waxing-crescent',
  'maya': 'maya-5',
  'alchemy': 'alchemy-fire',
  'rune': 'rune-fehu',
  'character': 'chiikawa',
  'gender': 'gender-female',
  'accessibility': 'accessibility',
  'kana': 'hiragana-a',
  'ai': 'any-to-any',
  'loading': 'loading-spinner',
  'cloud': 'cloud-upload',
  'weather': 'cloud-sun',
  'chart': 'chart-bar',
  'media': 'play-circle',
  'meeting': 'mic',
  'photo': 'camera',
  'screen': 'laptop',
  'money': 'wallet',
  'building': 'home',
  'git': 'git-branch',
  'keyboard': 'kbd-command',
  'dev': 'code',
  'rating': 'rating-mpa-pg13',
  'quality': '4k',
  'science': 'atom',
  'circuit': 'resistor',
  'math': 'sigma',
  'license': 'cc',
  'religion': 'religion-buddhism',
  'symbol': 'yin-yang',
  'mark': 'size-m',
  'laundry': 'laundry-wash',
  'hazard': 'radioactive',
  'ghs': 'ghs-flammable',
  'resin': 'resin-1',
  'okta': 'okta-4',
  'shopping': 'cart',
  'food': 'coffee',
  'nature': 'tree',
  'hardware': 'cpu',
  'notation': 'notation-treble-clef',
  'instrument': 'guitar',
  'weapon': 'sword',
  'clothing': 't-shirt',
  'controller': 'xbox-a',
  'tabletop': 'chess-knight',
  'award': 'trophy',
  'sport': 'soccer',
  'medical': 'first-aid',
  'mood': 'mood-happy',
  'game': 'dice-5',
  'object': 'compass',
  'ui': 'settings',
}

// 按完整图标集（不受搜索过滤影响）算一次：每个分类的成员和第一个图标
const ICONS_OF = new Map(categorize(icons).map(c => [c.id, c.groups.flatMap(g => g.icons.map(i => i.name))]))

export function categoryIcon(id) {
  const names = ICONS_OF.get(id) ?? []
  return names.includes(PICKS[id]) ? PICKS[id] : names[0]
}
